### ISSUE TITLE
Breaks on Linux / OS X when no hostname is present.

### ISSUE THREAD

**Issue by tstrimple** [Johnhhorton/node-nmap#9]
The scan breaks due to this line:

https://github.com/Johnhhorton/node-nmap/blob/master/index.js#L124

Non-Windows operating systems return "\n", not "\r\n".

**Comment by Johnhhorton** [comment]
Thanks for catching that.  I'll check this on a vm and fix it.

**Comment by Johnhhorton** [comment]
Added additional check for \n
